# Generated by Django 4.1.13 on 2024-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Чикен')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('price', models.IntegerField(verbose_name='500')),
            ],
        ),
    ]
