# Generated by Django 4.1.13 on 2024-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
